import type { School } from './types';

export const mockSchools: School[] = [
  {
    id: '1',
    name: 'Nanyang Primary School',
    address: '52 King\'s Road',
    postalCode: '268081',
    distance: 0.8,
    distanceBand: '1km',
    pressure: 'high',
    intakeChange: 'no-change',
    totalVacancies: 40,
    registeredStudents: 180,
    ballotChance: 22,
    ccas: ['Chinese Orchestra', 'Wushu', 'Art Club', 'Badminton'],
    affiliation: 'Nanyang Girls\' High School',
    specialPrograms: ['Applied Learning Programme (Chinese)', 'Learning for Life Programme'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 40, registered: 180, balloted: true, ballotRate: 22 },
      { year: 2024, phase: '2C', vacancies: 42, registered: 165, balloted: true, ballotRate: 25 },
      { year: 2023, phase: '2C', vacancies: 38, registered: 155, balloted: true, ballotRate: 24 },
      { year: 2022, phase: '2C', vacancies: 40, registered: 140, balloted: true, ballotRate: 29 },
      { year: 2021, phase: '2C', vacancies: 45, registered: 130, balloted: true, ballotRate: 35 },
    ],
    coordinates: { lat: 1.3191, lng: 103.8028 },
  },
  {
    id: '2',
    name: 'Raffles Girls\' Primary School',
    address: '21 Anderson Road',
    postalCode: '259978',
    distance: 1.2,
    distanceBand: '1-2km',
    pressure: 'high',
    intakeChange: 'decrease',
    intakeChangeValue: -5,
    totalVacancies: 35,
    registeredStudents: 156,
    ballotChance: 18,
    ccas: ['Choir', 'Ballet', 'Swimming', 'Debate'],
    affiliation: 'Raffles Girls\' School',
    specialPrograms: ['Bilingual Programme', 'Music Elective Programme'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 35, registered: 156, balloted: true, ballotRate: 18 },
      { year: 2024, phase: '2C', vacancies: 40, registered: 148, balloted: true, ballotRate: 27 },
      { year: 2023, phase: '2C', vacancies: 38, registered: 142, balloted: true, ballotRate: 27 },
      { year: 2022, phase: '2C', vacancies: 42, registered: 135, balloted: true, ballotRate: 31 },
      { year: 2021, phase: '2C', vacancies: 40, registered: 128, balloted: true, ballotRate: 31 },
    ],
    coordinates: { lat: 1.3066, lng: 103.8196 },
  },
  {
    id: '3',
    name: 'Anglo-Chinese School (Primary)',
    address: '50 Barker Road',
    postalCode: '309918',
    distance: 1.5,
    distanceBand: '1-2km',
    pressure: 'moderate',
    intakeChange: 'no-change',
    totalVacancies: 60,
    registeredStudents: 85,
    ballotChance: 71,
    ccas: ['Football', 'Basketball', 'Scouts', 'Band'],
    affiliation: 'Anglo-Chinese School (Independent)',
    specialPrograms: ['Sports Excellence Programme'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 60, registered: 85, balloted: false },
      { year: 2024, phase: '2C', vacancies: 58, registered: 72, balloted: false },
      { year: 2023, phase: '2C', vacancies: 55, registered: 68, balloted: false },
      { year: 2022, phase: '2C', vacancies: 60, registered: 75, balloted: false },
      { year: 2021, phase: '2C', vacancies: 62, registered: 82, balloted: false },
    ],
    coordinates: { lat: 1.3192, lng: 103.8372 },
  },
  {
    id: '4',
    name: 'Henry Park Primary School',
    address: '1 Holland Grove Road',
    postalCode: '278790',
    distance: 2.3,
    distanceBand: '2km+',
    pressure: 'high',
    intakeChange: 'increase',
    intakeChangeValue: 10,
    totalVacancies: 50,
    registeredStudents: 145,
    ballotChance: 34,
    ccas: ['Robotics', 'Tennis', 'Drama', 'Art'],
    specialPrograms: ['Applied Learning Programme (STEM)'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 50, registered: 145, balloted: true, ballotRate: 34 },
      { year: 2024, phase: '2C', vacancies: 40, registered: 128, balloted: true, ballotRate: 31 },
      { year: 2023, phase: '2C', vacancies: 42, registered: 115, balloted: true, ballotRate: 37 },
      { year: 2022, phase: '2C', vacancies: 45, registered: 108, balloted: true, ballotRate: 42 },
      { year: 2021, phase: '2C', vacancies: 48, registered: 98, balloted: true, ballotRate: 49 },
    ],
    coordinates: { lat: 1.3089, lng: 103.7856 },
  },
  {
    id: '5',
    name: 'Fairfield Methodist School (Primary)',
    address: '101 Tanjong Pagar Road',
    postalCode: '088524',
    distance: 0.5,
    distanceBand: '1km',
    pressure: 'low',
    intakeChange: 'no-change',
    totalVacancies: 80,
    registeredStudents: 45,
    ballotChance: 100,
    ccas: ['Choir', 'Badminton', 'Art Club', 'Scouts'],
    affiliation: 'Fairfield Methodist Secondary School',
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 80, registered: 45, balloted: false },
      { year: 2024, phase: '2C', vacancies: 78, registered: 42, balloted: false },
      { year: 2023, phase: '2C', vacancies: 82, registered: 48, balloted: false },
      { year: 2022, phase: '2C', vacancies: 80, registered: 52, balloted: false },
      { year: 2021, phase: '2C', vacancies: 85, registered: 55, balloted: false },
    ],
    coordinates: { lat: 1.2772, lng: 103.8444 },
  },
  {
    id: '6',
    name: 'CHIJ St. Nicholas Girls\' School (Primary)',
    address: '501 Victoria Street',
    postalCode: '198382',
    distance: 3.2,
    distanceBand: '2km+',
    pressure: 'moderate',
    intakeChange: 'decrease',
    intakeChangeValue: -8,
    totalVacancies: 55,
    registeredStudents: 78,
    ballotChance: 71,
    ccas: ['String Ensemble', 'Netball', 'Dance', 'Photography'],
    affiliation: 'CHIJ St. Nicholas Girls\' School (Secondary)',
    specialPrograms: ['Music Programme', 'Values in Action'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 55, registered: 78, balloted: false },
      { year: 2024, phase: '2C', vacancies: 63, registered: 85, balloted: false },
      { year: 2023, phase: '2C', vacancies: 60, registered: 72, balloted: false },
      { year: 2022, phase: '2C', vacancies: 58, registered: 68, balloted: false },
      { year: 2021, phase: '2C', vacancies: 62, registered: 75, balloted: false },
    ],
    coordinates: { lat: 1.3033, lng: 103.8589 },
  },
  {
    id: '7',
    name: 'Tao Nan School',
    address: '49 Marine Crescent',
    postalCode: '449761',
    distance: 1.8,
    distanceBand: '1-2km',
    pressure: 'high',
    intakeChange: 'no-change',
    totalVacancies: 45,
    registeredStudents: 168,
    ballotChance: 27,
    ccas: ['Chinese Chess', 'Wushu', 'Band', 'Swimming'],
    specialPrograms: ['Applied Learning Programme (Chinese Culture)'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 45, registered: 168, balloted: true, ballotRate: 27 },
      { year: 2024, phase: '2C', vacancies: 45, registered: 155, balloted: true, ballotRate: 29 },
      { year: 2023, phase: '2C', vacancies: 42, registered: 148, balloted: true, ballotRate: 28 },
      { year: 2022, phase: '2C', vacancies: 48, registered: 142, balloted: true, ballotRate: 34 },
      { year: 2021, phase: '2C', vacancies: 50, registered: 135, balloted: true, ballotRate: 37 },
    ],
    coordinates: { lat: 1.3036, lng: 103.9142 },
  },
  {
    id: '8',
    name: 'Rosyth School',
    address: '21 Serangoon North Avenue 4',
    postalCode: '555854',
    distance: 0.6,
    distanceBand: '1km',
    pressure: 'moderate',
    intakeChange: 'increase',
    intakeChangeValue: 15,
    totalVacancies: 70,
    registeredStudents: 92,
    ballotChance: 76,
    ccas: ['Robotics', 'Football', 'Choir', 'Art'],
    affiliation: 'Serangoon Gardens Secondary School',
    specialPrograms: ['Applied Learning Programme (STEM)', 'Learning for Life Programme (Arts)'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 70, registered: 92, balloted: false },
      { year: 2024, phase: '2C', vacancies: 55, registered: 78, balloted: false },
      { year: 2023, phase: '2C', vacancies: 58, registered: 82, balloted: false },
      { year: 2022, phase: '2C', vacancies: 52, registered: 75, balloted: false },
      { year: 2021, phase: '2C', vacancies: 50, registered: 68, balloted: false },
    ],
    coordinates: { lat: 1.3561, lng: 103.8711 },
  },
  {
    id: '9',
    name: 'Pei Hwa Presbyterian Primary School',
    address: '10 Pei Wah Avenue',
    postalCode: '509159',
    distance: 2.1,
    distanceBand: '2km+',
    pressure: 'low',
    intakeChange: 'no-change',
    totalVacancies: 85,
    registeredStudents: 52,
    ballotChance: 100,
    ccas: ['Basketball', 'Drama', 'Scouts', 'Choir'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 85, registered: 52, balloted: false },
      { year: 2024, phase: '2C', vacancies: 82, registered: 48, balloted: false },
      { year: 2023, phase: '2C', vacancies: 80, registered: 45, balloted: false },
      { year: 2022, phase: '2C', vacancies: 78, registered: 42, balloted: false },
      { year: 2021, phase: '2C', vacancies: 75, registered: 38, balloted: false },
    ],
    coordinates: { lat: 1.3722, lng: 103.8456 },
  },
  {
    id: '10',
    name: 'Ai Tong School',
    address: '100 Bright Hill Drive',
    postalCode: '579646',
    distance: 1.4,
    distanceBand: '1-2km',
    pressure: 'moderate',
    intakeChange: 'no-change',
    totalVacancies: 65,
    registeredStudents: 88,
    ballotChance: 74,
    ccas: ['Chinese Orchestra', 'Basketball', 'Art', 'Dance'],
    specialPrograms: ['Applied Learning Programme (Chinese)'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 65, registered: 88, balloted: false },
      { year: 2024, phase: '2C', vacancies: 62, registered: 82, balloted: false },
      { year: 2023, phase: '2C', vacancies: 60, registered: 78, balloted: false },
      { year: 2022, phase: '2C', vacancies: 65, registered: 85, balloted: false },
      { year: 2021, phase: '2C', vacancies: 68, registered: 92, balloted: false },
    ],
    coordinates: { lat: 1.3611, lng: 103.8356 },
  },
  {
    id: '11',
    name: 'Maris Stella High School (Primary)',
    address: '10 Bartley Road',
    postalCode: '539849',
    distance: 0.9,
    distanceBand: '1km',
    pressure: 'low',
    intakeChange: 'increase',
    intakeChangeValue: 8,
    totalVacancies: 75,
    registeredStudents: 58,
    ballotChance: 100,
    ccas: ['Football', 'Band', 'Swimming', 'Robotics'],
    affiliation: 'Maris Stella High School (Secondary)',
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 75, registered: 58, balloted: false },
      { year: 2024, phase: '2C', vacancies: 67, registered: 52, balloted: false },
      { year: 2023, phase: '2C', vacancies: 65, registered: 48, balloted: false },
      { year: 2022, phase: '2C', vacancies: 62, registered: 45, balloted: false },
      { year: 2021, phase: '2C', vacancies: 60, registered: 42, balloted: false },
    ],
    coordinates: { lat: 1.3478, lng: 103.8722 },
  },
  {
    id: '12',
    name: 'Catholic High School (Primary)',
    address: '9 Bishan Street 22',
    postalCode: '579767',
    distance: 1.7,
    distanceBand: '1-2km',
    pressure: 'high',
    intakeChange: 'no-change',
    totalVacancies: 48,
    registeredStudents: 142,
    ballotChance: 34,
    ccas: ['Chinese Orchestra', 'Wushu', 'Football', 'Science Club'],
    affiliation: 'Catholic High School (Secondary)',
    specialPrograms: ['Special Assistance Plan (SAP)'],
    historicalData: [
      { year: 2025, phase: '2C', vacancies: 48, registered: 142, balloted: true, ballotRate: 34 },
      { year: 2024, phase: '2C', vacancies: 48, registered: 138, balloted: true, ballotRate: 35 },
      { year: 2023, phase: '2C', vacancies: 45, registered: 128, balloted: true, ballotRate: 35 },
      { year: 2022, phase: '2C', vacancies: 50, registered: 135, balloted: true, ballotRate: 37 },
      { year: 2021, phase: '2C', vacancies: 52, registered: 125, balloted: true, ballotRate: 42 },
    ],
    coordinates: { lat: 1.3556, lng: 103.8378 },
  },
];

export const phases = ['2A', '2B', '2C', '2C Supplementary', '3'];
export const years = ['2025', '2024', '2023', '2022', '2021'];
export const distanceBands = [
  { value: '1', label: 'Within 1km' },
  { value: '2', label: '1-2km' },
  { value: '3', label: 'Over 2km' },
  { value: 'all', label: 'All distances' },
];
export const pressureLevels = [
  { value: 'all', label: 'All pressure levels' },
  { value: 'low', label: 'Low pressure' },
  { value: 'moderate', label: 'Moderate pressure' },
  { value: 'high', label: 'High pressure' },
];
